### ISSUE TITLE
Allow us to change the CorsProxy used by CosmosAsync

### ISSUE THREAD

**Issue by fucksophie** [spicetify/cli#3118]
### 📝 Provide a description of the new feature

In experimental settings or in spicetify's config, provide a option to change the cors proxy from the default `https://cors-proxy.spicetify.app` URL.

### ➕ Additional Information

This would allow us to bypass the issues with Genius in Lyrics Plus.

**Comment by rxri** [comment]
Our proxy works in the way that no cors proxy works (`<cors-proxy>/<domain to be proxied>`). Most of the proxies work in the way of `<cors-proxy>/?<domain>`. We would also need to add a way to configure the endpoint but it's not really the best idea because regardless if we would add it or not, the initial proxy will always be cors proxy. I don't think that's needed. If you want genius, I recommend editing the source code to use fetch and cors proxy of your choice
