### ISSUE TITLE
Feature to patch the spotify binary to disable forced dark mode

### ISSUE THREAD

**Issue by Covkie** [spicetify/cli#3150]
### 📝 Provide a description of the new feature

Currently spotify builds their binaries with the `force-dark-mode` flag. Would be nice to have an optional feature to patch this out.

Can be achieved by replacing `666F7263652D6461726B2D6D6F6465`(hex for `force-dark-mode`)  with `000000000000000000000000000000`(Null chars) in the Spotify binary

### ➕ Additional Information

See https://github.com/JulienMaille/spicetify-dynamic-theme/issues/87 for Linux & MacOS & https://github.com/JulienMaille/spicetify-dynamic-theme 's README for the existing powershell windows script

**Comment by rxri** [comment]
We’re not going to patch the binary though.

**Comment by rxri** [comment]
Niche feature that only small amount of people will use (dynamic theme users) or even probably won't because most of them install this theme via marketplace and do not know about the "force-dark-mode" thing. We wouldn't make it default either because it break stuff so, let just it be how it is now. CLI doesn't need to be bloated even more. We never patched binary either, and we won't, only for some force dark mode thingy
