### ISSUE TITLE
loopyloop extension not working

### ISSUE THREAD

**Issue by sentestlk** [spicetify/cli#3175]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.40.599.g606b7f29
- Spicetify version: v2.38.3
```

### 📝 Description

when I enter the `spicetify config extensions loopyLoop.js` in the cmd, the Spicetify extension is installed and after the installation the extension can't be used in Spotify. ( not showing start & end in when right click on play bar )

Is this the [reason](https://github.com/spicetify/cli/issues/3135#issuecomment-2287968570) why the Spicetify extension is not working?

**Comment by machinemessiah** [comment]
Works fine for me (_though my Spotify version is 1.2.45, so yours is a little older_); could you check whether there are any messages in the console that might indicate the point of failure and post them here? (_press ctrl+shift+i to open the devtools, just in case you're not familiar_)

Also, do you have other extensions that might be interfering with Loopy Loop or which affect the progress bar in any way (_best just to list all extensions you have installed, and also the theme you're using since it could be as simple as a purely CSS-based z-index issue_).

**Comment by rxri** [comment]
Works just fine for me on 1.2.47.
