### ISSUE TITLE
Enable enter on search

### ISSUE THREAD

**Issue by asgerkromand** [spicetify/cli#3176]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.45.454.gc16ec9f6
- Spicetify version: v2.38.3
```

### 📝 Description

I use the keyboardshortcut extension, and I'm trying to use the 'F'-key aka. keyboard-driven navigation. The issue happens when I navigate to the search bar and then type in e.g. an artist's name. 

Here I would then like to be able to press 'F' and jump to a given result from the search, but this is not possible as I'm still in the search bar. I then try to press Esc to get out of the search bar, but this deletes the search-keywords and the search results disappear. If instead I try to press enter to get out of the search bar, while keeping the search-keywords - and thus the search result - this is not possible neither.

In sum, I reckon it is not possible to use 'F' to get to the results without using e.g. tab. Could it be possible to add the 'Enter' as a possible key to press to get out of the search bar while keeping your search results, so that you can use the 'F'-key to go into the results.

### 📸 Screenshots

<img width="985" alt="billede" src="https://github.com/user-attachments/assets/ff24570b-d31f-4d3c-9164-87c601099153">

**Comment by UmairRaaz** [comment]
I want to work in this

**Comment by AishwaryaAgr** [comment]
Please review PR with the bug fixed

**Comment by rien333** [comment]
> Here I would then like to be able to press 'F' and jump to a given result from the search, but this is not possible as I'm still in the search bar. I then try to press Esc to get out of the search bar, but this deletes the search-keywords and the search results disappear.

I think this can be closed for now, because this is no longer how spotify (`v1.2.47.364.gf06e5cee`) behaves. This is probably because the search functionality has been revamped.

Specifically, the following steps should do what OP wants:

1. Start a search, either by clicking the search field, or pressing <kbd>/</kbd> (when https://github.com/spicetify/cli/issues/3200 is resolved)
2. Press <kbd>ESC</kbd> twice
3. Press <kbd>f</kbd> to start hinting (that's what it's properly called, not "Vim mode", as it says in the source code)

**Comment by rxri** [comment]
When you will click enter while search bar is focused, it will stop being focused and you will be able to use vim keybinds.
